// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Proyecto2.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Proyecto2 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object A=null;
  public static Object B=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=30;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=32;
      A=$fix($opIntvlY('a','z'));
      $line=33;
      B=$fix($opIntvlY('0','9'));
      $line=34;
      Object coder=$fix(Proyecto2.createCoder());
      $line=35;
      Object deCoder=$fix(Proyecto2.createDecoder());
      $line=42;
      Utilities.testCodeDecode($cast(gold.structures.automaton.ITransducer.class,coder),$cast(gold.structures.automaton.ITransducer.class,deCoder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"main",$line);
    }
  }
  public static ITransducer createCoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=53;
      gold.structures.set.ISet $v1=$newSet();
      $v2:for (Object d:GCollections.unmodifiableCollection($opIntvlY('a','z'))) {
        for (Object s:GCollections.unmodifiableCollection($opIntvlY('0','7'))) {
          int $v3=$int(0);
          int $v4=$int(8)-1;
          for (int pos=$v3; pos<=$v4; pos++) {
            $v1.add(GCollections.asList(d,s,pos));
          }
        }
      }
      Object Q=$fix($opUnionY($v1,GCollections.asSet("I","Error","$","tj","t$","ts")));
      $line=55;
      Object \u03A3=$fix($opIntvlY('a','z'));
      $line=56;
      Object \u03A3_=$fix($opUnionY(\u03A3,GCollections.asSet('$')));
      $line=57;
      Object q_0=$fix("I");
      $line=58;
      gold.structures.set.ISet $v5=$newSet();
      $v6:for (Object d:GCollections.unmodifiableCollection($opIntvlY('a','z'))) {
        for (Object s:GCollections.unmodifiableCollection($opIntvlY('0','7'))) {
          for (Object pos:GCollections.singletonCollection(0)) {
            $v5.add(GCollections.asList(d,s,pos));
          }
        }
      }
      Object F=$fix($v5);
      $line=60;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,q_0,F,new GMethod(Proyecto2.class,"\u03B4"),new GMethod(Proyecto2.class,"g"),new GMethod(Proyecto2.class,"h")});
      if (true) break $try;
      $line=61;
      $rethrow(new RuntimeException("The function \"createCoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"createCoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=68;
      if (($opEqualY(state,"I")&&$opMembrY(input,$opIntvlY('a','z')))) {
        $line=68;
        $result=input;
        if (true) break $try;
      }
      else {
        $line=69;
        if (($opMembrY(state,$opIntvlY('a','z'))&&$opMembrY(input,$opIntvlY('a','z')))) {
          $line=70;
          if ($opEqualY($getArrayValue(state,new Object[]{2}),1)) {
            $line=71;
            Object $v7=input;
            Object $v8=$getArrayValue(state,new Object[]{1});
            Object $v9=$getArrayValue(state,new Object[]{2});
            Object d=$fix($v7);
            Object s=$fix($v8);
            Object pos=$fix($v9);
          }
          $line=73;
          if ($opEqualY(input,$getArrayValue(state,new Object[]{0}))) {
            $line=73;
            $result="t$";
            if (true) break $try;
          }
          else {
            $line=74;
            if (!$opEqualY(input,$getArrayValue(state,new Object[]{0}))) {
              $line=74;
              $result="tj";
              if (true) break $try;
            }
            else {
              $line=75;
              if ($opEqualY($getArrayValue(state,new Object[]{2}),7)) {
                $line=75;
                $result="ts";
                if (true) break $try;
              }
            }
          }
        }
        else {
          $line=77;
          if (($opEqualY($opAbsolY(state),7)&&$opMembrY(input,$opIntvlY('a','z')))) {
            $line=78;
            Object $v10=$getArrayValue(state,new Object[]{0});
            Object $v11=$getArrayValue(state,new Object[]{1});
            Object $v12=$getArrayValue(state,new Object[]{2});
            Object d=$fix($v10);
            Object s=$fix($v11);
            Object pos=$fix($v12);
            $line=79;
            $result=GCollections.asList(d,s,$opModulY($opAdditY(pos,1),8));
            if (true) break $try;
          }
          else {
            $line=80;
            $result="E";
            if (true) break $try;
          }
        }
      }
      $line=82;
      $rethrow(new RuntimeException("The function \"\u03B4(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=85;
      if (($opEqualY(state,"I")&&$opMembrY(input,$opIntvlY('a','z')))) {
        $line=86;
        Object $v13=input;
        Object $v14=$getArrayValue(state,new Object[]{1});
        Object $v15=$getArrayValue(state,new Object[]{2});
        Object d=$fix($v13);
        Object s=$fix($v14);
        Object pos=$fix($v15);
        $line=87;
        $result=input;
        if (true) break $try;
      }
      else {
        $line=88;
        if (($opMembrY(state,$opIntvlY('a','z'))&&$opMembrY(input,$opIntvlY('a','z')))) {
          $line=89;
          Object $v16=$getArrayValue(state,new Object[]{0});
          Object $v17=$getArrayValue(state,new Object[]{1});
          Object $v18=$getArrayValue(state,new Object[]{2});
          Object d=$fix($v16);
          Object s=$fix($v17);
          Object pos=$fix($v18);
          $line=90;
          if ($opEqualY(input,d)) {
            $line=90;
            s=$fix($opAdditY(s,1));
            $line=90;
            $result="";
            if (true) break $try;
          }
          else {
            $line=91;
            if ($opEqualY(state,"tj")) {
              $line=91;
              $result=pos;
              if (true) break $try;
            }
            else {
              $line=92;
              if ($opEqualY(state,"t$")) {
                $line=92;
                $result='$';
                if (true) break $try;
              }
              else {
                $line=93;
                if ($opEqualY(state,"ts")) {
                  $line=93;
                  $result=s;
                  if (true) break $try;
                }
                else {
                  $line=94;
                  $result=GCollections.asList(d,s,$opModulY($opAdditY(pos,1),8));
                  if (true) break $try;
                }
              }
            }
          }
        }
        else {
          $line=96;
          $result="";
          if (true) break $try;
        }
      }
      $line=100;
      $rethrow(new RuntimeException("The function \"h(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=106;
      $result="";
      if (true) break $try;
      $line=107;
      $rethrow(new RuntimeException("The function \"g(s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"g",$line);
    }
    return $result;
  }
  public static ITransducer createDecoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=110;
      gold.structures.set.ISet $v19=$newSet();
      $v20:for (Object d:GCollections.unmodifiableCollection(GCollections.asSet(3,2,5))) {
        for (Object s:GCollections.unmodifiableCollection($opIntvlY('a','z'))) {
          for (Object pos:GCollections.unmodifiableCollection($opUnionY($opIntvlY(0,4),GCollections.asSet("_")))) {
            $v19.add(GCollections.asList(d,s,pos));
          }
        }
      }
      Object Q=$fix($opUnionY($v19,GCollections.asSet(3,2,5,"I","E")));
      $line=111;
      Object \u03A3_=$fix($opUnionY($opIntvlY('a','z'),GCollections.asSet(':','2','3','5')));
      $line=112;
      Object \u03A3=$fix($opUnionY(\u03A3_,GCollections.asSet('#')));
      $line=113;
      Object q_0=$fix("I");
      $line=114;
      gold.structures.set.ISet $v21=$newSet();
      $v22:for (Object d:GCollections.unmodifiableCollection(GCollections.asSet(3,2,5))) {
        for (Object s:GCollections.unmodifiableCollection($opIntvlY('a','z'))) {
          int $v23=$int(0);
          int $v24=$int(5)-1;
          for (int pos=$v23; pos<=$v24; pos++) {
            $v21.add(GCollections.asList(d,s,pos));
          }
        }
      }
      Object F=$fix($v21);
      $line=116;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u03A3_,q_0,F,new GMethod(Proyecto2.class,"\u03B41"),new GMethod(Proyecto2.class,"g"),new GMethod(Proyecto2.class,"h1")});
      if (true) break $try;
      $line=117;
      $rethrow(new RuntimeException("The function \"createDecoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"createDecoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B41(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=123;
      if (($opEqualY(state,"I")&&$opMembrY(input,GCollections.asSet('2','3','5')))) {
        $line=123;
        $result=$opSubtrY(input,'0');
        if (true) break $try;
      }
      else {
        $line=124;
        if (($opMembrY(state,GCollections.asSet(2,3,5))&&$opMembrY(input,$opIntvlY('a','z')))) {
          $line=124;
          $result=GCollections.asList(state,input,"_");
          if (true) break $try;
        }
        else {
          $line=125;
          $result="E";
          if (true) break $try;
        }
      }
      $line=127;
      $rethrow(new RuntimeException("The function \"\u03B41(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"\u03B41",$line);
    }
    return $result;
  }
  public static Object \u03B41(java.lang.Iterable $v25, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v26=GCollections.unmodifiableCollection($v25).iterator();
      Object d=$v26.next();
      Object s=$v26.next();
      Object pos=$v26.next();
      $line=130;
      if (($opEqualY(pos,"_")&&$opEqualY(input,':'))) {
        $line=130;
        $result=GCollections.asList(d,s,1);
        if (true) break $try;
      }
      else {
        $line=131;
        if ($opEqualY(pos,"_")) {
          $line=131;
          $result="E";
          if (true) break $try;
        }
        else {
          $line=132;
          if (($opEqualY(input,'#')&&!$opEqualY(pos,0))) {
            $line=132;
            $result="E";
            if (true) break $try;
          }
          else {
            $line=133;
            if (($opEqualY(input,s)&&$opEqualY(pos,0))) {
              $line=133;
              $result="E";
              if (true) break $try;
            }
            else {
              $line=134;
              if ($opMembrY(input,$opUnionY($opIntvlY('a','z'),GCollections.asSet('#')))) {
                $line=134;
                $result=GCollections.asList(d,s,$opModulY($opAdditY(pos,1),d));
                if (true) break $try;
              }
              else {
                $line=135;
                $result="E";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=137;
      $rethrow(new RuntimeException("The function \"\u03B41(\u27E8d,s,pos\u27E9:java.lang.Iterable,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"\u03B41",$line);
    }
    return $result;
  }
  public static Object h1(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=143;
      if (($opEqualY(state,"I")&&$opMembrY(input,GCollections.asSet('2','3','5')))) {
        $line=143;
        $result=$opSubtrY(input,'0');
        if (true) break $try;
      }
      else {
        $line=144;
        if (($opMembrY(state,GCollections.asSet(2,3,5))&&$opMembrY(input,$opIntvlY('a','z')))) {
          $line=144;
          $result=input;
          if (true) break $try;
        }
        else {
          $line=145;
          $result="";
          if (true) break $try;
        }
      }
      $line=147;
      $rethrow(new RuntimeException("The function \"h1(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"h1",$line);
    }
    return $result;
  }
  public static Object h1(java.lang.Iterable $v27, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v28=GCollections.unmodifiableCollection($v27).iterator();
      Object d=$v28.next();
      Object s=$v28.next();
      Object pos=$v28.next();
      $line=150;
      if (($opEqualY(pos,"_")&&$opEqualY(input,':'))) {
        $line=150;
        $result=input;
        if (true) break $try;
      }
      else {
        $line=151;
        if (($opEqualY(input,'#')&&$opEqualY(pos,0))) {
          $line=151;
          $result=s;
          if (true) break $try;
        }
        else {
          $line=152;
          if (($opMembrY(input,$opIntvlY('a','z'))&&$opEqualY(pos,1))) {
            $line=152;
            $result=Proyecto2.shiftSymbol(input,$opMinusY(d));
            if (true) break $try;
          }
          else {
            $line=153;
            if ($opMembrY(input,$opIntvlY('a','z'))) {
              $line=153;
              $result=input;
              if (true) break $try;
            }
            else {
              $line=154;
              $result="";
              if (true) break $try;
            }
          }
        }
      }
      $line=156;
      $rethrow(new RuntimeException("The function \"h1(\u27E8d,s,pos\u27E9:java.lang.Iterable,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"h1",$line);
    }
    return $result;
  }
  public static Object shiftSymbol(Object symbol, Object shift) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=164;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=166;
      if ($opMembrY(symbol,$opIntvlY('a','z'))) {
        $line=167;
        r=$cast(Character.class,$fix($opAdditY('a',$opModulY($opAdditY($opSubtrY(symbol,'a'),shift),26))));
      }
      else {
        $line=168;
        if ($opMembrY(symbol,$opIntvlY('A','Z'))) {
          $line=169;
          r=$cast(Character.class,$fix($opAdditY('A',$opModulY($opAdditY($opSubtrY(symbol,'A'),shift),26))));
        }
        else {
          $line=170;
          if ($opMembrY(symbol,$opIntvlY('0','9'))) {
            $line=171;
            r=$cast(Character.class,$fix($opAdditY('0',$opModulY($opAdditY($opSubtrY(symbol,'0'),shift),10))));
          }
          else {
            $line=172;
            r=$cast(Character.class,$fix(r));
          }
        }
      }
      $line=174;
      $result=r;
      if (true) break $try;
      $line=175;
      $rethrow(new RuntimeException("The function \"shiftSymbol(symbol:Object,shift:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Proyecto2.class,"shiftSymbol",$line);
    }
    return $result;
  }
}
